backend:
  name: git-gateway
  branch: "main"
publish_mode: editorial_workflow
media_folder: "assets/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - label: "About"
        name: "about"
        file: "about.md"
        fields:
          - {
              label: "Title",
              name: "title",
              widget: "hidden",
              default: "about",
            }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "about",
            }
          - {
              label: "Show header",
              name: "show_header",
              widget: "boolean",
              default: false,
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Resume"
        name: "resume"
        file: "resume.md"
        fields:
          - {
              label: "Title",
              name: "title",
              widget: "hidden",
              default: "resume",
            }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "resume",
            }
          - {
              label: "Show header",
              name: "show_header",
              widget: "boolean",
              default: false,
            }
          - { label: "Body", name: "body", widget: "markdown" }
